add scrfd(.onnx) model
sophgo/model-zoo pull request #113
Opened 2023-02-08 09:46 UTC by hengyang123

2023-02-10 06:16 UTC, Jeffwhen requested changes

2023-02-10 06:16 UTC, Jeffwhen commented on .gitattributes
> +vision/recognition/scrfd/scrfd_mlir_config.yaml filter=lfs diff=lfs merge=lfs -text
config 文件不用 LFS 提交。

2023-02-10 06:16 UTC, Jeffwhen commented on .gitattributes
> +vision/recognition/scrfd/scrfd_500m_kps.onnx filter=lfs diff=lfs merge=lfs -text
所有 .onnx 会自动以 LFS 提交，这里不用指定。

2023-02-13 06:18 UTC, Jeffwhen commented
+ Rebase 一下；
+ `vision/recognition/scrfd/scrfd_mlir_config.yaml` 这个文件不要以 LFS 上传。

2023-02-13 13:32 UTC, hengyang123 commented
Files Changed 做了修改

2023-02-16 09:56 UTC, closed without merging