add lprnet
sophgo/model-zoo pull request #152
Opened 2023-03-14 08:41 UTC by hengyang123

name,shape,gops,time(ms),mac_utilization,cpu_usage,ddr_utilization
lprnet_bm1684x_int8_asym,1x3x24x94,30.960,0.443,218.28%,5.00%,14.75%
lprnet_bm1684x_f32,1x3x24x94,30.960,0.729,2124.36%,5.00%,27.43%
lprnet_bm1684x_int8_sym,1x3x24x94,30.960,0.440,219.94%,5.00%,14.51%

SOPHGO Toolchain v0.8.299-g9e37af59-20230307
libsophon 0.4.5

2023-03-15 02:35 UTC, Jeffwhen requested changes

2023-03-15 02:35 UTC, Jeffwhen commented on vision/detection/lprnet/README.md
> +[COCO2017](https://cocodataset.org/)
数据集不对？

2023-03-15 06:51 UTC, hengyang123 commented on vision/detection/lprnet/README.md
> +[COCO2017](https://cocodataset.org/)
贴的是cali用的数据集，

2023-03-17 07:57 UTC, XiangBin-gh commented
合并成一笔提交

2023-03-17 09:23 UTC, hengyang123 commented
已合并

2023-03-20 13:11 UTC, closed without merging