tsm v2
sophgo/model-zoo pull request #160
Opened 2023-03-18 19:42 UTC by seriphdog

###submit to github
1) has add to default_cases.txt
2) Pr Info:
2.1) performance in stat.csv:
name,shape,gops,time(ms),mac_utilization,cpu_usage,ddr_utilization
name,shape,gops,time(ms),mac_utilization,cpu_usage,ddr_utilization
tsm_bm1684x_Bf16,1x3x8x224x224,65.554,22.381,146.45%,6.00%,61.78%
tsm_bm1684x_f16,1x3x8x224x224,65.554,22.401,146.32%,6.00%,61.73%
tsm_bm1684x_f32,1x3x8x224x224,65.554,86.062,38.09%,11.00%,32.78%
compilation,1x3x8x224x224,65.554,22.406,N/A,6.00%,N/A
compilation,1x3x8x224x224,65.554,86.085,N/A,11.00%,N/A
compilation,1x3x8x224x224,65.554,22.403,N/A,6.00%,N/A
fp32:flops: 65554824720, runtime: 62.249783ms, ComputationAbility: 1.053093T
fp16:flops: 65554824720, runtime: 21.997709ms, ComputationAbility: 2.980075T
bf16:flops: 65554824720, runtime: 21.997709ms, ComputationAbility: 2.980075T
2.2)tpu-mlir:
branch:master
commit id: 315ccc9a5ba3b401039e399fd6f8cdc92f70c78b
2.3)libsophon:0.4.5

2023-03-18 19:47 UTC, seriphdog commented
tsm pr && tsm v1 can be delete

2023-03-20 07:56 UTC, XiangBin-gh commented
run_cali如果没问题就打开

2023-03-20 12:14 UTC, seriphdog commented
> run_cali如果没问题就打开
run_cali 得到的table有问题，具体在一层slice切成2个Local片，第一个slice片的min=max=thre=0会触发assert，故注释掉。

2023-03-21 16:39 UTC, Jeffwhen requested changes

2023-03-21 16:43 UTC, Jeffwhen requested changes

2023-03-21 16:43 UTC, Jeffwhen commented on dataset/tiny-kinetics-400/tsm_cali_table
放模型目录中 data 目录

2023-03-21 16:43 UTC, Jeffwhen commented on dataset/tiny-kinetics-400/top_output_tsm.npz
放模型目录中 data 目录

2023-03-21 16:43 UTC, Jeffwhen commented on dataset/tiny-kinetics-400/tiny_kinetic_calibration/1.npy
放模型目录中 data 目录

2023-03-21 16:43 UTC, Jeffwhen commented on dataset/tiny-kinetics-400/input_tsm.npz
非通用数据，放模型目录中 data 目录

2023-03-23 17:44 UTC, seriphdog commented on vision/recognition/tsm/README.md
> +None
已加入工程链接

2023-03-23 17:44 UTC, seriphdog commented on vision/recognition/tsm/README.md
> +This is a implementation of the Temporal Shift Module described in the paper
补充模型描述

2023-03-23 17:44 UTC, seriphdog commented on vision/recognition/tsm/tsm.mlir.config.yaml
> +  model_deploy.py
所有model_transform.py都加了-

2023-03-23 17:44 UTC, seriphdog commented on vision/recognition/tsm/README.md
> +We sugguest use tiny dataset(<https://github.com/Tramac/tiny-kinetics-400>) rather than large Kinetic-400.
已修改

2023-03-23 17:45 UTC, seriphdog commented on vision/recognition/tsm/README.md
> +|Proposed       |TSM_kinetics_RGB_resnet50_shift8_blockres_avg_segment8_e50.pth|
已修改成示例

2023-03-23 17:45 UTC, seriphdog commented on dataset/tiny-kinetics-400/top_output_tsm.npz
数据全部换到了tsm/data下面

2023-03-25 05:28 UTC, seriphdog commented on dataset/tiny-kinetics-400/tiny_kinetic_calibration/1.npy
数据全部换到了tsm/data下面

2023-03-25 05:28 UTC, seriphdog commented on dataset/tiny-kinetics-400/input_tsm.npz
数据全部换到了tsm/data下面

2023-03-25 07:47 UTC, seriphdog commented on vision/recognition/tsm/README.md
> +This is a implementation of the Temporal Shift Module described in the paper
paper链接已放入下方inference

2023-03-28 03:03 UTC, seriphdog commented
githubstatus已正常，已rebase

2023-03-29 07:28 UTC, Jeffwhen commented
rebase 成一笔，full_cases.list 有冲突不用管，最后合入时候处理下就行。

2023-03-29 13:42 UTC, seriphdog commented on dataset/tiny-kinetics-400/tsm_cali_table
done

2023-03-29 13:43 UTC, seriphdog commented
> rebase 成一笔，full_cases.list 有冲突不用管，最后合入时候处理下就行。

Done

2023-03-31 02:42 UTC, merged