add a navigation table and check codes
sophgo/model-zoo pull request #161
Opened 2023-03-20 05:27 UTC by wangyx95

model-zoo首页README.md文件中添加了模型导航表。
.github/workflows/check.py中添加了检测导航表的代码，即，model-zoo中添加新模型路径 vision or language/class/name后，要在导航表中加入对应的模型：

|Net class|Net name                                                      |nntc|mlir|
|:---------|:------------------------------------------------|:----|:----|
|class      |[name](vision or language/class/name)         |  \*  |  \*  |

其中vision or language/class/name需要是model-zoo中的文件夹，若模型支持nntc(mlir)，则在相应列添加符号 '*'。表格需要对齐。

2023-03-21 17:29 UTC, Jeffwhen requested changes

2023-03-21 17:29 UTC, Jeffwhen commented on .github/workflows/check.py
> +def model_links_should_be_valid(file, lines):
链接有效性有另外一个回归检查，不用代码实现

2023-03-21 17:29 UTC, Jeffwhen commented on .github/workflows/check.py
> +    for idx, line in enumerate(lines):
- 要以配置文件为单位检查，同一目录下 `name` 字段相同的认为分别是 nntc 和 mlir 配置文件；
- 要检查 nntc 和 mlir 的状态是否正确；
- `### Model navigation ` 章节直接用 `re.match` 去搜，一个函数内完成，不要写太长。

2023-03-22 01:49 UTC, wangyx95 commented on .github/workflows/check.py
> +    for idx, line in enumerate(lines):
前两点没太明白，我之前检查的逻辑是目录下有‘*config.yaml‘文件时，若文件名中有'mlir'字段，则支持mlir，否则支持nntc。
这里`name`字段相同没有理解，如果只有一个配置文件，如何判断支持nntc还是mlir。

2023-03-22 02:03 UTC, wangyx95 commented on README.md
> +|asr      |[conformer](language/asr/conformer)                | \* |    |
[vision/classification/inception_v4](https://github.com/sophgo/model-zoo/tree/main/vision/classification/inception_v4)下的config.yaml文件和mlir.config.yaml文件 `name`字段不同该如何处理，导航表要写两行吗？[vision/detection/yolov5](https://github.com/sophgo/model-zoo/tree/main/vision/detection/yolov5)也有同样的问题，该路径下有多个config.yaml文件和mlir.config.yaml文件，`name`字段也都不相同。

2023-03-24 13:30 UTC, closed without merging