face alignment fp32 bmodel
sophgo/model-zoo pull request #165
Opened 2023-03-22 08:09 UTC by greensun0830

在mlir的sdk环境下将face_align模型转换为bmodel，芯片要求支持1684x，fp32已跑通，int8 run time error，可能有算子不支持。

2023-03-23 10:49 UTC, Jeffwhen requested changes

2023-03-23 10:49 UTC, Jeffwhen commented on vision/detection/face_alignment/README.md
> +[FaceX-Zoo](https://github.com/JDAI-CV/FaceX-Zoo/tree/main/face_sdk)
paper 链接

2023-03-23 10:49 UTC, Jeffwhen commented on vision/recognition/face_alignment/cali_table
不传。

2023-03-24 07:20 UTC, XiangBin-gh commented
需要附上runtime测试数据

2023-03-25 06:01 UTC, greensun0830 commented
name,shape,gops,time(ms),mac_utilization,cpu_usage,ddr_utilization
face_alignment_bm1684x_int8_asym,1x3x112x112,39.285,1233.937,0.10%,790.40%,0.02%
face_alignment_bm1684x_f32,1x3x112x112,39.285,724.765,2.71%,793.30%,0.04%
face_alignment_bm1684x_int8_sym,1x3x112x112,39.285,939.836,0.13%,794.50%,0.01%

2023-03-27 03:24 UTC, XiangBin-gh commented
runtime实测数据需要提供编译器及驱动版本号，另外现在target不要直接写1684x

2023-03-29 13:05 UTC, closed without merging