add big_transfer_mlir
sophgo/model-zoo pull request #170
Opened 2023-03-26 16:17 UTC by grybd

name,shape,gops,time(ms),mac_utilization,cpu_usage,ddr_utilization
big_transfer_bm1684x_f16,1x3x224x224,8.854,1.830,241.88%,8.00%,40.25%
big_transfer_bm1684x_int8_sym,1x3x224x224,8.854,1.131,24.47%,7.00%,34.91%
big_transfer_bm1684x_Bf16,1x3x224x224,8.854,1.832,241.60%,7.00%,40.20%
big_transfer_bm1684x_f32,1x3x224x224,8.854,8.435,52.48%,5.00%,17.50%
compilation,1x3x224x224,8.854,1.829,N/A,5.00%,N/A
compilation,1x3x224x224,8.854,1.130,N/A,10.00%,N/A
compilation,1x3x224x224,8.854,1.832,N/A,7.00%,N/A
compilation,1x3x224x224,8.854,8.457,N/A,5.00%,N/A

2023-03-29 03:12 UTC, XiangBin-gh commented
config文件有新的命名规范，另外实测数据需要提供对应工具链版本号及驱动版本号，测试建议先升级tpu_perf再测试

2023-03-29 07:20 UTC, grybd commented
> config文件有新的命名规范，另外实测数据需要提供对应工具链版本号及驱动版本号，测试建议先升级tpu_perf再测试

好的

2023-03-31 02:44 UTC, Jeffwhen requested changes

2023-03-31 02:44 UTC, Jeffwhen commented on vision/classification/big_transfer_mlir/cali_table
不上传 calitable，直接走 cali 流程。

2023-03-31 03:09 UTC, grybd commented on vision/classification/big_transfer_mlir/cali_table
生成cali_table bug 需要解一下，我先注释吧

2023-04-03 06:24 UTC, Jeffwhen commented
不能编译 INT8 模型？

2023-04-05 15:57 UTC, grybd commented
> 不能编译 INT8 模型？

是的，目前是生成cali_table生成的阈值最后有3个layer的最大最小值都是0,应该是bug，已经提jira需要解下

2023-04-13 03:02 UTC, grybd commented
> 不能编译 INT8 模型？

目前可以编译int8了

2023-04-20 15:37 UTC, grybd commented
![1682004994070](https://user-images.githubusercontent.com/52237830/233416608-b95c1f75-ed6d-4a1e-9228-c4c5b55e6f05.png)
感觉是网络的问题？

2023-04-27 06:38 UTC, merged