fix harness config && add automatic check(stable)
sophgo/model-zoo pull request #345
Opened 2023-07-03 02:36 UTC by grybd

2023-07-03 09:59 UTC, Jeffwhen requested changes

2023-07-03 09:59 UTC, Jeffwhen commented on .github/workflows/check.py
> +                harness_args_dict = config['BM1684X'].get('harness')
```
for harness in recursive_iter(config):
    assert xxx
```

2023-07-04 02:54 UTC, Jeffwhen commented
```python3
def key_value_iter(d):
    if type(d) == list:
        for v in d:
            for k, v in key_value_iter(v):
                yield k, v
    elif type(d) == dict:
        for dk, dv in d.items():
            for k, v in key_value_iter(dv):
                yield k, v
            yield dk, dv

def config_harness_name_should_be_standard(path):
    for fn in walk(path):
        if not fn.endswith('config.yaml'):
            continue
        with open(fn, mode='r', encoding='utf-8') as f:
            config = yaml.load(f.read(), Loader=yaml.FullLoader)
            name_set = set()
            for k, v in key_value_iter(config):
                if k != 'harness':
                    continue
                assert 'args' in v, f'harness.args does not exist in {fn}'
                for arg in v['args']:
                    assert 'name' in arg, f'harness.args.name does not exist in {fn}'
                name = arg['name']
                assert name not in name_set, \
                    f'Duplicate harness arg name \"{name}\" in {fn}'
                name_set.add(name)
```

2023-07-04 06:07 UTC, grybd commented
> ```python
> def key_value_iter(d):
>     if type(d) == list:
>         for v in d:
>             for k, v in key_value_iter(v):
>                 yield k, v
>     elif type(d) == dict:
>         for dk, dv in d.items():
>             for k, v in key_value_iter(dv):
>                 yield k, v
>             yield dk, dv
> 
> def config_harness_name_should_be_standard(path):
>     for fn in walk(path):
>         if not fn.endswith('config.yaml'):
>             continue
>         with open(fn, mode='r', encoding='utf-8') as f:
>             config = yaml.load(f.read(), Loader=yaml.FullLoader)
>             name_set = set()
>             for k, v in key_value_iter(config):
>                 if k != 'harness':
>                     continue
>                 assert 'args' in v, f'harness.args does not exist in {fn}'
>                 for arg in v['args']:
>                     assert 'name' in arg, f'harness.args.name does not exist in {fn}'
>                 name = arg['name']
>                 assert name not in name_set, \
>                     f'Duplicate harness arg name \"{name}\" in {fn}'
>                 name_set.add(name)
> ```
已经修改，在这段代码基础上加上一个target_list 避免 不同target 的harness name 相同 出现误报的问题 @Jeffwhen

2023-07-04 06:31 UTC, Jeffwhen requested changes

2023-07-04 06:31 UTC, Jeffwhen commented on .github/workflows/check.py
> +                name = arg['name']
这几行缩进不对

2023-07-04 06:31 UTC, Jeffwhen commented on .github/workflows/check.py
> +                name_set = set()
这一行直接诺到 438 行。

2023-07-04 06:50 UTC, grybd commented on .github/workflows/check.py
> +                name_set = set()
已修改

2023-07-04 06:50 UTC, grybd commented on .github/workflows/check.py
> +                name = arg['name']
已修改

2023-07-04 08:49 UTC, merged