add retinaface
sophgo/model-zoo pull request #69
Opened 2022-12-14 06:30 UTC by muccry

rongyu.chen retinaface

2022-12-21 08:49 UTC, muccry commented
add retinaface

2022-12-22 03:00 UTC, muccry commented
add retinaface

2022-12-24 10:23 UTC, Jeffwhen requested changes

2022-12-24 10:23 UTC, Jeffwhen commented on vision/detection/.gitattributes
> +*.onnx filter=lfs diff=lfs merge=lfs -text
.onnx 在外面有 track,这里不需要再 track.

2022-12-24 10:23 UTC, Jeffwhen commented on vision/detection/retinaface/README.md
> +* retinaface [here](https://github.com/deepinsight/insightface/tree/master/detection/retinaface)
模型权重从哪里来的?项目的地址呢?

2022-12-24 10:23 UTC, Jeffwhen commented on vision/detection/retinaface/config.yaml
> +gops: 88.6
1x3x640x640 的 gops 不可能这么大.

2022-12-26 06:22 UTC, merged